# Generated by Django 6.0 on 2026-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_salon_channel_message_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_files/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="contenu",
            field=models.TextField(blank=True),
        ),
    ]
